/*
 * generated by Xtext 2.16.0
 */
package io.typefox.examples.theia.states


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StatesStandaloneSetup extends StatesStandaloneSetupGenerated {

	def static void doSetup() {
		new StatesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
