/*
 * generated by Xtext 2.16.0
 */
package io.typefox.examples.theia.states


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StatesRuntimeModule extends AbstractStatesRuntimeModule {
}
