/*
 * generated by Xtext 2.16.0
 */
package io.typefox.examples.theia.states.tests

import com.google.inject.Inject
import io.typefox.examples.theia.states.states.StateMachine
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(StatesInjectorProvider)
class StatesParsingTest {
	@Inject
	ParseHelper<StateMachine> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			statemachine MrsGrantsSecretCompartments
			
			event doorClosed
			event drawOpened
			event lightOn
			event panelClosed
			
			state active
				lightOn	=> waitingForDraw
				drawOpened => waitingForLight
			
			state idle
				doorClosed => active
			
			state waitingForLight 
				lightOn => idle
			
			state waitingForDraw
				drawOpened => unlockedPanel
			
			state unlockedPanel
				panelClosed => idle
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
