/*
 * generated by Xtext 2.16.0
 */
package io.typefox.examples.theia.states.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class StatesScopeProvider extends AbstractStatesScopeProvider {

}
